### ISSUE TITLE
How to Cmake? and Cmake error

### ISSUE THREAD

**Issue by jeok70** [rpavlik/wiiuse#63]
I'm use Cmake example generate .cmake but Not excute and generate .sln but Not excute 

How to do the Issue?

**Comment by janoc** [comment]
Hello, 

I am sorry, but I am not quite sure what your problem is. Are you asking how to run CMake to generate a Visual Studio solution file?

Make a build folder, then switch to it and run cmake-gui and then click configure & generate buttons. That should make you a .sln file you can open using Visual Studio. 

Or do you have an error message from CMake? If yes, then please post the entire output, otherwise nobody can help you.

**Comment by jeok70** [comment]
![11140112_1165889880091188_8417505253990405588_n](https://cloud.githubusercontent.com/assets/9250952/10714366/eba9c3d6-7b27-11e5-8cdb-25e184d39e05.jpg)

**Comment by jeok70** [comment]
<img width="643" alt="default" src="https://cloud.githubusercontent.com/assets/9250952/10714930/e96a56dc-7b3e-11e5-8744-f44f88808365.PNG">

**Comment by janoc** [comment]
That has nothing to do with CMake. Your compilation has failed, because the wiiuse.lib was not built (or found) for some reason. The unresolved symbols are only a consequence of that. 

Without knowing your code and how you have set up your project I can't really help you more. This is basic Visual Studio stuff, nothing particularly specific to Wiiuse.

**Comment by jeok70** [comment]
Dear janoc
I hope that with wiiuse 0.12 as a wiiuse.dll can call, because I want to write Cython.
Like: http://sourceforge.net/projects/wiiuse/

But I'm stuck in these issues.
So I want to move my project? Show code?

**Comment by janoc** [comment]
That is absolutely ancient Wiiuse. Why are  you taking the unmaintained code from SourceForge and then reporting issues here? Please, get the most recent version from Github (i.e. https://github.com/rpavlik/wiiuse ). That code should at the very least compile.

Now concerning your own integration with Cython, that be possible, I believe. Wiiuse will produce a C DLL that you can call from Python.

**Comment by jeok70** [comment]
So Src compiled from inside Source Code DLL it?

**Comment by janoc** [comment]
Sorry, I don't understand what you mean. You need to compile the Wiiuse source code into a DLL, yes.

**Comment by jeok70** [comment]
Thank you I'm Try

**Comment by jeok70** [comment]
Sorry I ask a issue  How to  Wiiuse source code  into a DLL ?
And  What is  DLL,.Lib  difference between ?

**Comment by janoc** [comment]
To build shared libs (DLL) from Wiiuse you need to have BUILD_WIIUSE_SHARED_LIB enabled in the CMake options, but I believe that is the default setting. 

Re difference between DLL and lib - sorry, but that is basic stuff. I suggest you check out Microsoft's documentation on dynamic libraries. They explain what is a DLL, what an static and import library is.

**Comment by jeok70** [comment]
Cmake issue  show the image 
![1445774668075](https://cloud.githubusercontent.com/assets/9250952/10715507/b5b7107c-7b53-11e5-96ea-42f1dbf777d2.jpg)
![1445774735612](https://cloud.githubusercontent.com/assets/9250952/10715511/e1b0ffd0-7b53-11e5-80fd-b571eed74879.jpg)

**Comment by janoc** [comment]
Sorry, but that image is completely useless. You need to copy the actual text error message (the complete text that is around that "Configuring incomplete, errors occurred!" message) , not the final warning that there is a problem.

**Comment by jeok70** [comment]
![1445775071529](https://cloud.githubusercontent.com/assets/9250952/10715528/96869118-7b54-11e5-98f5-9568f31a441b.jpg)
Is this?

**Comment by janoc** [comment]
OK, that's better. You need to install the Windows Development kit, the HID libraries that Wiiuse needs are part of it. Then set the WINHID_ROOT_DIR to the folder where you have installed it and it should find it. 

You should be able to find the right one here: https://msdn.microsoft.com/en-us/windows/hardware/gg454513.aspx (download the correct one for your version of Windows).

**Comment by jeok70** [comment]
HID libraries is where ?

I'm install wdk sucess ，but I'm not found  HID libraries .
WINHID_ROOT_DIR is what?

**Comment by janoc** [comment]
Actually, what you need is the Microsoft Windows Driver Development Kit, not the regular Development kit (or Platform SDK or whatever the thing was called).

WINHID_ROOT_DIR is variable specifying where did you install the Development kit. If CMake doesn't find it automatically, you can set the the variables in CMake GUI as follows:

WINHID_LIBRARY=full name with path to libhid.lib  
WINHID_CRT_INCLUDE_DIR=folder path where inc/crt/stdio.h is
WINHID_INCLUDE_DIR=folder path where  hidsdi.h is

**Comment by jeok70** [comment]
New issue  show the image 
![1445780889028](https://cloud.githubusercontent.com/assets/9250952/10715927/3e33395e-7b62-11e5-8d89-f85766ae3b53.jpg)

**Comment by jeok70** [comment]
![1445783067630](https://cloud.githubusercontent.com/assets/9250952/10716078/61422194-7b67-11e5-8054-250a244f0ef6.jpg)
Could NOT find GLUT (missing:  GLUT_glut_LIBRARY GLUT_INCLUDE_DIR) 
What is it?  I don't have the variable

**Comment by janoc** [comment]
That should be alright. But the examples need SDL and GLUT libraries, so either disable building of the examples (BUILD_EXAMPLE & BUILD_EXAMPLE_SDL) or install those.

**Comment by jeok70** [comment]
That the new issue , I'm run the Cmake ，and I'm remove BUILD_EXAMPLE_SDL variable 
Configuring WiiUse version 0.14.2
   Entering             C:/Users/丁/Desktop/wiiuse-master/src
   Returning to         C:/Users/丁/Desktop/wiiuse-master
Configuring done
this is error message 

I'm not found item

**Comment by janoc** [comment]
You shouldn't remove the variable but uncheck the checkbox instead.

The message from your last post doesn't show any errors - if you think you have an error, you MUST post the entire output, not only a snippet.

**Comment by jeok70** [comment]
<img width="355" alt="default" src="https://cloud.githubusercontent.com/assets/9250952/10716251/5de5f72c-7b6d-11e5-86df-aa2bdab2eca8.PNG">
This is sucess?  
<img width="574" alt="2" src="https://cloud.githubusercontent.com/assets/9250952/10716264/bac73460-7b6d-11e5-92fb-5972ffcff9c3.PNG">
I'm not Found build floder any item and Only have src example floder

**Comment by jeok70** [comment]
inside the src example  floder any not  found item

**Comment by janoc** [comment]
You need to click the Generate button after running Configure. That will generate a Visual Studio solution file.

**Comment by jeok70** [comment]
Thank you

**Comment by jeok70** [comment]
My Cmake issue  is about image
<img width="519" alt="4" src="https://cloud.githubusercontent.com/assets/9250952/10716626/fc548462-7b79-11e5-9925-8923c9674112.PNG">

**Comment by jeok70** [comment]
My Cmake version 3.3.2

**Comment by janoc** [comment]
You can ignore that warning. The Wiiuse build system needs to be updated for newer CMake.

**Comment by jeok70** [comment]
Sorry My  Visual Studio 2013 solution  generate error 
vcrutime.h

**Comment by jeok70** [comment]
Sorry My  Visual Studio 2013 solution  generate error 
cannot open file  vcrutime.h

**Comment by janoc** [comment]
I am sorry, but Visual Studio 2013 doesn't come with that file. Are you sure you aren't mixing up Visual Studio versions (like using Visual Studio 2015)? 

Anyhow, that has nothing to do with Wiiuse. Something with your Visual Studio setup is wrong.

**Comment by jeok70** [comment]
My Visual Studio 2013 is community Version 
How to  mixing up Visual Studio versions  ?
Rebuild Cmake?

**Comment by janoc** [comment]
The file vcruntime.h exists only in Visual C++ 14 (i.e. Visual Studio 2015). So you have something set up incorrectly. This file is not used by Wiiuse anywhere.

**Comment by jeok70** [comment]
I'm install the  Visual C++ 14, but generate new error 
about the Image
<img width="672" alt="error3" src="https://cloud.githubusercontent.com/assets/9250952/10750987/0396ae88-7cb7-11e5-884f-4c9b447b3a48.PNG">

**Comment by jeok70** [comment]
Thank you

**Comment by jeok70** [comment]
Sorry,I'm ask a new issue the example.exe
Why  have the Debug Message?

**Comment by janoc** [comment]
Sorry, but if you don't post the error message, how am I supposed to know why you have got it? I can't see your screen ...

**Comment by jeok70** [comment]
Sorry,about the screen 
<img width="688" alt="default" src="https://cloud.githubusercontent.com/assets/9250952/10753584/0c9f227e-7ccd-11e5-9bfe-7ce2e9a710ee.PNG">
The DEBUG Message What is it? 
The Message is that exmaple.c  generate ?

**Comment by janoc** [comment]
Ah. That is actually a debugging message used to debug problems with the Wiimote protocol. It appears if you build the library in Debug configuration. Switch to Release and it will be gone.

In other words, those messages are harmless, they are there only for debugging and when you have compiled in the Debug configuration.

**Comment by jeok70** [comment]
Thank you 

OK

**Comment by jeok70** [comment]
My wiimote is not have motionplus.

Is my wiimote can use motionplus Struct angle_rate_gyro ?

**Comment by janoc** [comment]
Well, if you don't have Motion+ then those values are obviously not going to be meaningful. 

angle_rate_gyro is angular velocity, I believe. However, I am not sure about the scale/units, you will need to check the code and the documentation for that.
