### ISSUE TITLE
Compile error osx 10.11

### ISSUE THREAD

**Issue by thomasgeissl** [rpavlik/wiiuse#67]
I am not able to compile wiiuse on my osx 10.11 machine. 
```sh
dhcp-10-176-88-115:build thomasgeissl$ make
Scanning dependencies of target wiiuse
[  5%] Building C object src/CMakeFiles/wiiuse.dir/classic.c.o
[ 11%] Building C object src/CMakeFiles/wiiuse.dir/dynamics.c.o
[ 17%] Building C object src/CMakeFiles/wiiuse.dir/events.c.o
[ 23%] Building C object src/CMakeFiles/wiiuse.dir/guitar_hero_3.c.o
[ 29%] Building C object src/CMakeFiles/wiiuse.dir/io.c.o
[ 35%] Building C object src/CMakeFiles/wiiuse.dir/ir.c.o
[ 41%] Building C object src/CMakeFiles/wiiuse.dir/nunchuk.c.o
[ 47%] Building C object src/CMakeFiles/wiiuse.dir/wiiuse.c.o
/Users/thomasgeissl/programming/libs/wiiuse/src/wiiuse.c:661:12: warning: address of array 'req->data' will
      always evaluate to 'true' [-Wpointer-bool-conversion]
        if (!req->data || !req->len) {
            ~~~~~~^~~~
1 warning generated.
[ 52%] Building C object src/CMakeFiles/wiiuse.dir/wiiboard.c.o
[ 58%] Building C object src/CMakeFiles/wiiuse.dir/motion_plus.c.o
[ 64%] Building C object src/CMakeFiles/wiiuse.dir/util.c.o
[ 70%] Building C object src/CMakeFiles/wiiuse.dir/os_mac/os_mac.m.o
[ 76%] Building C object src/CMakeFiles/wiiuse.dir/os_mac/os_mac_interface.m.o
[ 82%] Building C object src/CMakeFiles/wiiuse.dir/os_mac/os_mac_find.m.o
[ 88%] Linking C shared library libwiiuse.dylib
Undefined symbols for architecture x86_64:
  "_wiiuse_os_ticks", referenced from:
      _wiiuse_wait_report in io.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libwiiuse.dylib] Error 1
make[1]: *** [src/CMakeFiles/wiiuse.dir/all] Error 2
make: *** [all] Error 2
```

2e81a87fbef20bd4f54d2b1c5532e8b5829ce7c0 compiles fine.
Any pointers?

**Comment by janoc** [comment]
Arg. I think that that function isn't actually implemented for Mac yet. That function is needed for being able to support a recovery from connection problems. 

Unfortunately, neither me nor Ryan have a Mac, so I can't really fix this. A patch would be really appreciated here. If you want to give it a shot, try to take an inspiration in the wiiuse_os_ticks() function in os_nix.c. Apparently, Mac doesn't clock_gettime(), so you will need to use something like this to get the time:
https://gist.github.com/jbenet/1087739

**Comment by thomasgeissl** [comment]
Thanks for the hint. I will give it a try and keep you updated.

**Comment by janoc** [comment]
The Mac-specific code is the os_mac subfolder. I am not really sure what the deal with those .m files is, though. But I am not a Mac developer.

**Comment by lysannschlegel** [comment]
.m is the file ending for Objective-C files. When you want to use Mac system APIs it's either C or preferably Objective-C.


    _____________________________

**Comment by janoc** [comment]
Yeah, that's what I have assumed that it is too, but I have never used Objective-C before.

**Comment by thomasgeissl** [comment]
I will have a look tomorrow and PR.
