### ISSUE TITLE
Wiimote use Python wiiuse error

### ISSUE THREAD

**Issue by jeok70** [rpavlik/wiiuse#69]
Excuse me my wiiuse generator error

error message is 
""
"[WARNING] Packet ignored.  This may indicate a problem (timeout is 5 ms)."

What the message  is mean?

and my wiimote reach realtime motion sessing is not good

**Comment by janoc** [comment]
Hello, 

That message is harmless, it is warning emitted in the Windows HID code. You can update to the latest Git version, the message is silenced there. 

Jan

**Comment by jeok70** [comment]
Ok, so that message is not ignored  Sensoer Data?

**Comment by janoc** [comment]
No, that message was a bit incorrect - it actually meant that it took more than 5ms to receive data. Simply the Wiimote didn't respond in time. That could happen for many reasons (Wiimote could be busy, perhaps it has nothing to report, there could be expansion being connected at that exact moment, etc.), so the message itself is not that useful and I have removed it in the current version. 

The message doesn't really indicate a problem, you can ignore it.
