### ISSUE TITLE
How to load wiiuse.dll

### ISSUE THREAD

**Issue by jeok70** [rpavlik/wiiuse#70]
I'm use C++ language, and How to load wiiuse.dll?

**Comment by jeok70** [comment]
OR How to C# languege call wiiuse

**Comment by janoc** [comment]
Hello,

I am sorry, but the issue tracker is for tracking bugs in the library, not to provide support with basic programming questions. 

You can certainly find answers to both of your questions on Google - search for C++ library linking and in C# how to use the P/Invoke mechanism or managed C++. 

Good luck.
