### ISSUE TITLE
Question about unique ID

### ISSUE THREAD

**Issue by mlantin** [rpavlik/wiiuse#78]
Is there a way to get a unique ID per device connected, like a serial number? Something that is the same every time I execute an application that links to the wiimotes? Also needs to be cross-platform.

**Comment by paulomotta** [comment]
I think the bluetooth address is unique, isn't it?

--
Paulo Motta
--
"Qualquer tecnologia suficientemente avançada é indistinguível da mágica" -
Arthur C. Clarke

**Comment by mlantin** [comment]
yes I believe it would be. but I wondered if the bluetooth address would be constant across platforms (windows/Mac) and whether there is a way to access it that is the same across platforms.

**Comment by lysannschlegel** [comment]
MAC addresses are usually hard-wired into the device, so they would be the same across platforms.But they are not guaranteed to be unique: manufacturers do reuse addresses, but they try to ship them across the world to reduce chance of conflict. I'm not sure if this is true for all the manufacturers or only the cheaper ones, though.If you have two devices with the same MAC address, I think you cannot operate either of them properly at the same time. You could use them one after another, though, but they would appear as the same MAC address.
So maybe a combination of these would be better, and guaranteed to be unique: https://developer.bluetooth.org/TechnologyOverview/Pages/DIS.aspxAdd it sounds like these are just fixed values you can query, should be constant across platforms. The only question is, which combination makes it unique?
		_____________________________

**Comment by janoc** [comment]
You can certainly use a MAC address - that is hardwired in the Wiimote/Bluetooth chipset firmware and certainly doesn't change between Windows/Linux/Mac etc.

Re uniqueness - I wouldn't worry about that too much. The address space is so large that the chances of getting two devices with the same address is almost zero. In the 20 years that I am dealing with computers I have seen only a single case of a MAC address conflict - and that was between two 3com Ethernet cards in the late 90s.

It certainly won't happen if you use genuine Nintendo hardware. 3rdparty manufacturers could potentially use a conflicting address, but again, that's more a theoretical than practical risk. Moreover, as others said before, if you have two devices with identical MAC, they will not work at the same time, so it is easy to detect that something is amiss. 

> So maybe a combination of these would be better, and guaranteed to be unique: https://developer.bluetooth.org/TechnologyOverview/Pages/DIS.aspx And it sounds like these are just fixed values you can query, should be constant across platforms. The only question is, which combination makes it unique? Edit: That "System ID" sounds good...

That assumes that the manufacturer actually follows the standard and puts something sensible in there. Most don't, especially those that bend the standard for their proprietary needs already (like Nintendo - or Sony). Others implement just the bare minimum that makes the device to work, so you are likely to find garbage data there. 

> whether there is a way to access it that is the same across platforms.
Unfortunately not.  This depends a lot on the Bluetooth stack implementation and that is very different between platforms (and even stacks, as in Windows there are several incompatible options). If someone knows about a wrapper library abstracting this, I would be very interested in one. A lot of problems in Wiiuse stem from the platform-specific code.

**Comment by Baumgartl** [comment]
> In Linux you can get the MAC address from the struct wiimote_t, fields bdaddr and bdaddr_str. However, in Windows we don't have the address, only HANDLE. And on Mac it is yet different again.

I will try to add Bluetooth MAC address support under Windows as soon as my untested WiiUse version (based on v0.15.4) is ready for the upstream. According to some of my tests with a Wii Balance Board, [HidD_GetSerialNumberString()](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/hidsdi/nf-hidsdi-hidd_getserialnumberstring) looks very promising.

**Comment by janoc** [comment]
Well, feel free to submit a pull request.

**Comment by rpavlik** [comment]
Frankly, if you're using them regularly, you may very well be good co-maintainer material. I used to use them daily, now I rarely do...
