### ISSUE TITLE
[MacOS Sierra] Wiimote not detected by wiiuse but found by dolphin

### ISSUE THREAD

**Issue by cboulay** [rpavlik/wiiuse#83]
Using MacOS Sierra.

The controller is a black Wiimote that shows up in bluetooth preferences as Nintendo RVL-CNT-01. The below behaviours are identical whether I have the motion plus attached or not.

When I first connect the controller, all 4 LEDs continuously flash. In this state, if I run wiiuseexample I get the following output.

```
wiiuse v0.15.0 loaded.
  Fork at http://github.com/rpavlik/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> http://wiiuse.net
[DEBUG] /Volumes/STORE/Tools/Misc/wiiuse/src/os_mac/os_mac_find.m:211: Inquiry complete, error=0, aborted=NO
[DEBUG] /Volumes/STORE/Tools/Misc/wiiuse/src/os_mac/os_mac_find.m:211: Inquiry complete, error=0, aborted=YES
[ERROR] Unable to stop bluetooth device inquiry.
[INFO] Found 0 Wiimote device(s).
No wiimotes found.
Program ended with exit code: 0
```

If I open dolphin controller configuration then press the "Refresh" button, the controller vibrates twice, the LEDs stop flashing and instead I get a solid single LED1. In this state, the messages from wiiuseexample are identical.

```
wiiuse v0.15.0 loaded.
  Fork at http://github.com/rpavlik/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> http://wiiuse.net
[DEBUG] /Volumes/STORE/Tools/Misc/wiiuse/src/os_mac/os_mac_find.m:211: Inquiry complete, error=0, aborted=NO
[DEBUG] /Volumes/STORE/Tools/Misc/wiiuse/src/os_mac/os_mac_find.m:211: Inquiry complete, error=0, aborted=YES
[ERROR] Unable to stop bluetooth device inquiry.
[INFO] Found 0 Wiimote device(s).
No wiimotes found.
Program ended with exit code: 0
```

**Comment by janoc** [comment]
I am not a Mac user, but this "Unable to stop bluetooth device inquiry." sounds simply like a consequence of something else controlling the Bluetooth subsystem. 

If the Wiimote is paired to the Mac already (which the behaviour of Dolphin suggests), then **it will not** work with Wiiuse anymore. Wiiuse relies on the the Wiimote staying in the discoverable mode. If you pair it instead, then on newer Wiimotes pressing A+B will automatically make it connect to the last host it has been used with instead of becoming discoverable. Wiiuse will never be able to detect it in such case. You will likely have to use the red button in the battery compartment to force it into the discoverable/pairing mode again. 

I have looked at the Dolphin code, they are not using Wiiuse anymore and using hidapi instead. So they are relying on the Wiimote being paired using the standard OS services and then talk to it as to a normal HID device (= game controller).

**Comment by cboulay** [comment]
Thank you, that was it.

Maybe the MacOS section of the README can make this a little clearer? To someone with a little experience pairing difficult bluetooth devices (PSMove), it reads like "Sometimes pairing is incomplete. Disconnect and pair again." It's not clear that the controller CANNOT be paired and MUST BE in discoverable mode.

**Comment by janoc** [comment]
Could you make the modification and submit a pull request, please? Either me or @rpavlik  will merge it.

I am not a Mac user, don't even have the slightest idea how the Bluetooth is set up on a Mac, so I wouldn't be able to provide useful instructions there.

**Comment by cboulay** [comment]
Sure. Can you confirm that it is also necessary for Windows users to disconnect the device and make it discoverable before using it with wiiuse?

**Comment by janoc** [comment]
On Fri, Dec 9, 2016 at 4:23 PM, Chadwick Boulay <notifications@github.com>
wrote:

> Sure. Can you confirm that it is also necessary for Windows users to
> disconnect the device and make it discoverable before using it with wiiuse?
>

No, for Windows it works differently. In Windows you can't really pair it
without special software that can handle the protocol. However, you have to
connect it from the Bluetooth control panel in Windows before starting
Wiiuse-based app (without pairing).

**Comment by cboulay** [comment]
It's probably possible to get the behaviour to be the same in Mac as it is in Windows. i.e., it should be possible to pair & connect the device first, and not have to put it into discoverable mode, before using wiiuse. One way to achieve this would be to replace the Mac IO layer with hidapi. Or, find out which hidapi calls dolphin is using, find out the IOBluetooth calls those hidapi calls are using, then modify wiiuse's mac io layer accordingly.

I'm already involved in a complicated game controller repository ([PSMoveService](https://github.com/cboulay/PSMoveService)), among other responsibilities, so unfortunately I won't be taking on this challenge myself.

**Comment by janoc** [comment]
Yes, that could be doable, hidapi supports Mac already. I am thinking about migrating the Linux backend to hidapi as well, Linux now supports Wiimotes natively and there is no need for the hacked up communication code that is in Wiiuse anymore. 

However, neither @rpavlik nor me have a Mac, so unless a Mac developer decides to chip in, it is not likely to happen. 

I can pretty well understand the mess with PSMove, I did have to deal with that controller before and someone at Sony needs to have some unspeakable acts performed on them for the nonstandard dog's breakfast they have made from the Bluetooth HID protocol.

**Comment by cboulay** [comment]
If you ever get the Linux backend ported to hidapi then feel free to ping me. It should be trivial to port the Mac backend after that. In PSMoveService, and psmoveapi before it, there aren't any important differences between Mac & Linux in terms of how hidapi is used. I expect most of the necessary changes will be cmake related.

**Comment by janoc** [comment]
On Fri, Dec 9, 2016 at 5:10 PM, Chadwick Boulay <notifications@github.com>
wrote:

> If you ever get the Linux backend ported to hidapi then feel free to ping
> me. It should be trivial to port the Mac backend after that. In
> PSMoveService, and psmoveapi before it, there aren't any important
> differences between Mac & Linux in terms of how hidapi is used. I expect
> most of the necessary changes will be cmake related.
>

OK. I will need to find time and energy for that first, though :)

J.
