### ISSUE TITLE
Nunchuk handshake in pass-throgh mode

### ISSUE THREAD

**Issue by Gadir** [rpavlik/wiiuse#91]
Hi. I am trying to write a win32 console to use the wiimote as a controller for FPS. I have done something like that in GlovePIE, but this program seems very unrelieable, so I decided myself to write it in C (I am not an expert, as you can imagine). To do this I have been looking for a library that gives me support por IR, motionplus and nunchuk.

Wiiuse seemed to have all this, but the nunchuk in pass-though mode only gives me the joystick data (and not calibrated), it doesn't give me the acc data netiher the C and Z buttons. When I try a wiimote withput WM+ everythong is perfect with the nunchuk data. 

I guess the nunchuk in pass-through mode is missing its own initialization-handshake; I mean, this is done when the wiimote is a normal one, but not when there is a WM+ present, because in this case only the handshake of the WM+ is done, but nothing about the nunchuk.

Thank you very much.

**Comment by janoc** [comment]
Hello, 

That is odd, but we have seen all sorts of mess with Motion+ before ...  Which Wiimote and Nunchuck variant do you have? Is that a genuine (aka Nintendo) product? Or a clone? Many clones don't implement the protocol correctly so there all bets are off. 

Also, it would help if you could compile the example application from the Wiiuse folder (the text one, not the SDL one) in debug mode and run it, including trying to enable the Motion+ & nunchuck. And then post the output here. That will allow me to see what might be happening there.

**Comment by Gadir** [comment]
Hi, thank you very much for your response. 
All peripherals I have used (nunchuk, wiimote and wiimote with M+) are original Nintendo. And they are also from the Wii era - I mean, they are not the ones from the WIi U era, which I have read might be more inconsistent. They are not even of the "TR" kind, but the very first ones. I have also made the test with different elements, and the result was the same.
I will compile the example and copy the outpost, I hope you can see something.

**Comment by Gadir** [comment]
Ok, for what I have seen this is the problem.

The test I did (and in which I found the problems) was done with a shorter version of the example, in which I deleted all the code related to other extensions (classic controller, balance board, etc) and the motion sensing and M+ were activated from the start - you didn't have to press + or 1 to activate them, the activation were called at the beginning fo the start function. And then I couldn't get the proper data from the nunchuk.

However, in the complete example, this is not happening. And I believe this is because the motion sensing and M+ are activated later, when I press + and 1. I suppose this is the correct order: first do the handshake with the nunchuk in pass-through mode, then with the M+.

So I  guess and all I have to do is adding a delay for the activation of the M+, no doing it from the start. Or maybe I have to check whenever the handshake with the nunchuk is completed to activate the M+, I will try to figure it out (any advice would be welcome, anyway!)

Thank you very much again.

**Comment by janoc** [comment]
Yes, I think so - you need to first initialize the extension normally, if you turn on the M+, there is no extension initialized, it only changes the mode and whatever the extension sends will be integrated in the Motion+ reports. 

So you need to first initialize everything, turn on motion sensing and then, when you turn M+ on, the code selects the proper report to use (because it sees motion sensing was on) and will report the data.

**Comment by Gadir** [comment]
Thank again, sorry to have disturbed you

**Comment by janoc** [comment]
No need to apologize - just if you have managed to resolve the problem, can you, please, close the issue?
